apiVersion: v1
kind: Secret
metadata: 
  name: secret       # Name of the secret
type: Opaque         # Default type for arbitrary key/value data
data: 
  username: YWRtaW4=   # "admin" base64-encoded
  password: YWRtaW4xMjM= # "admin123" base64-encoded
