apiVersion: v1
kind: Service
metadata:
  name: nginx-np 
spec:
  type: NodePort
  selector:
    project: expense
    component: backend
    environment: dev
    demo: np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    component: backend-np
    environment: dev
    demo: np
spec:
  containers:
    - name: nginx
      image: nginx
