apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: backend
    environment: dev
    demo: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    component: backend-lb
    environment: dev
    demo: lb
spec:
  containers:
    - name: nginx
      image: nginx
