apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        # soft limit
        requests:
          cpu: "102m"
          memory: "256Mi"
        # hard limit
        limits:
          cpu: "122m"
          memory: "512Mi"